### ISSUE TITLE
Review Requirements for Paragraph Items

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#313]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## Conditions of satisfaction
All of the following tickets should be reviewed and approved:
- [ ](Needs review) Create Horizontal Line paragraph [az_quickstart #286](https://app.zenhub.com/workspace/o/az-digital/az_quickstart/issues/286)
- [ ](Needs review) Create HTML paragraph [az_quickstart #287](https://app.zenhub.com/workspace/o/az-digital/az_quickstart/issues/287)
- [ ](Needs review) Create Text with Background paragraph [az_quickstart #290](https://app.zenhub.com/workspace/o/az-digital/az_quickstart/issues/290)
- [ ](Needs review) Create Text on Media paragraph [az_quickstart #291](https://app.zenhub.com/workspace/o/az-digital/az_quickstart/issues/291)
- [ ](Needs review) Create View paragraph [az_quickstart #292](https://app.zenhub.com/workspace/o/az-digital/az_quickstart/issues/292)
- [ ](Needs review) Create Space paragraph [az_quickstart #294](https://app.zenhub.com/workspace/o/az-digital/az_quickstart/issues/294)

**Comment by danahertzberg** [comment]
Completed review and provided templates as needed.
