### ISSUE TITLE
Create Connect (Social Media) footer block

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#584]
Match functionality of Quickstart 1's "Connect Block (Social Media)" block

## Motivation
Allow for links with icons to social media accounts in footer

## Context
Quickstart 1 implementation: separate module

## Proposed QS2 resolution
- Menu similar to other footer menus with module to associate icons with the links.
- Need to associate icon class with each link.
- Use [menu links attribute module](https://www.drupal.org/project/menu_link_attributes).

### Requirements
- [x] Links appear in footer
- [x] Associated icons appear to left of the link
- [x] Default links go to main Arizona accounts
- [x] Links should be editable
- [x] Links for: Facebook, Twitter, Instagram, LinkedIn, Youtube

### Subtasks
1. Add menu links attribute module (Rebecca) #1169 
2. Add social media menu (Dana) #1171
3. Verify menu link styling looks good with Troy's PR https://github.com/az-digital/az_quickstart/issues/1012 
4. Update icon styling #1221

**Comment by smayden** [comment]
Module that associates icons with menu items:
https://git.drupalcode.org/project/simple_menu_icons

Relevant code from module:
https://git.drupalcode.org/project/simple_menu_icons/-/blob/8.x-2.x/simple_menu_icons.module

**Comment by michaelhagedon** [comment]
Is the last remaining piece of this to update the icon styling?

**Comment by smayden** [comment]
I think so for the social media piece. There is also a separate ticket that will create a module where you can enable the global footer with the default content in place. I believe there is some issue/blocker with that one.

**Comment by danahertzberg** [comment]
All requirements and subtasks are complete!
